### ISSUE TITLE
Agregar logos

### ISSUE THREAD

**Issue by diegobeauroyre** [mxabierto/cumbre-global#1]

**Comment by diegobeauroyre** [comment]
Todos los logos deberán ir hipervinculados:

Gobierno de la República y Presidencia a: www.presidencia.gob.mx
Mexico Digital: http://www.presidencia.gob.mx/edn/
OGP en español a : www.opengovpartnership.org/es
OGP en inglés a: http://www.opengovpartnership.org/
INAI: http://inicio.ifai.org.mx/

8 organizaciones: 
http://www.culturaecologica.org.mx/
http://fundar.org.mx/index.html/
http://imco.org.mx/home/
http://articulo19.org/
http://www.cidac.org/esp/index.php
http://www.gesoc.org.mx/site/
http://www.tm.org.mx/c/inicio/
http://socialtic.org/

**Comment by diegobeauroyre** [comment]
Aquí hay un sprite que podemos usar para los logos 


![](https://cloud.githubusercontent.com/assets/6226604/8141116/2de54b36-1128-11e5-9af1-572f21103755.png)

**Comment by diegobeauroyre** [comment]
Así es como quedarían
![](https://cloud.githubusercontent.com/assets/6226604/8141306/c425284e-112a-11e5-80a9-79a3da0b555c.png)

**Comment by jipster** [comment]
@jajs1975 acá están ya los logos

**Comment by jajs1975** [comment]
Una pregunta @jipster: de donde tomo los logos??, de la imagen de arriba??

**Comment by jipster** [comment]
@jajs1975 los logos están en blanco en el comentario anterior de diego, no se ven pero ahí están. @diegobeauroyre hay otra forma de pasárselos?

(de una vez agregar SFP y SRE)

**Comment by jajs1975** [comment]
A eso me refería Jorge, creo que sería adecuado que no los pasaran por separado, para que podamos encajarlos correctamente en la plantilla.

**Comment by jipster** [comment]
@diegobeauroyre se los pasas por favor.

**Comment by diegobeauroyre** [comment]
@jajs1975 @jipster Se los paso en unos momentos por separado pero es mejor práctica para estos casos usar un sprite como en el footer de http://gobabiertomx.org/ 

También: 
http://www.w3schools.com/css/css_image_sprites.asp

**Comment by diegobeauroyre** [comment]
@jajs1975 Acá los logos por separado: 

https://drive.google.com/folderview?id=0B6xuFjlJEb0NfkJUN01tRXlLSmZLNldFNENOTGlySzJIQnAxa0Y5S09rdjRzTlp0TnRhRUE&usp=sharing

**Comment by jipster** [comment]
@jajs1975 acá están los logos, por favor, si puedes por favor agrégalos tan pronto se pueda. era fundamental para nosotros que estuvieran arriba el lunes que se comparta la página.

**Comment by diegobeauroyre** [comment]
@jajs1975 
Hay que usar el logo del INAI en lugar del IFAI:

![inai-logo-blanco](https://cloud.githubusercontent.com/assets/6226604/8265202/9ef0571c-16b9-11e5-9079-3dffe74d17f4.png)
