### ISSUE TITLE
Revisar el navbar

### ISSUE THREAD

**Issue by jipster** [mxabierto/cumbre-global#105]
1. Fuera del index, el navbar no es igual todo el tiempo tanto en inglés como en español
2. Cambiar en el navbar en inglés y en español el OGP-SCO a OGP-CSO en todo el sitio

**Comment by JRedentor** [comment]
Buena tarde @jipster, una pregunta al respecto: ¿las páginas en inglés deben incluir en la barra las ligas a la página de OGP-U, o no?, además, si esto es afirmativo, ¿se debe ligar a la página de OGP-U en español o se debe crear una versión en inglés de dicha página?
Saludos.

**Comment by jipster** [comment]
@JRedentor OGP-U es sólo en la parte en español

**Comment by JRedentor** [comment]
Perfecto! gracias @jipster!

**Comment by JRedentor** [comment]
Buenos días @jipster! 
Podrían cerrar los issues que consideren atendidos, por favor.
Gracias y buen fin de semana!
@jajs1975
