### ISSUE TITLE
Agregar sección de hospitality

### ISSUE THREAD

**Issue by diegobeauroyre** [mxabierto/cumbre-global#109]
Aquí está la sección de hospitality: https://drive.google.com/a/dhb.mx/folderview?id=0BwdAZw_UiZSTLUYwQ1NGV2x3MkE&usp=sharing

**Comment by diegobeauroyre** [comment]
o de esto? @jajs1975

**Comment by diegobeauroyre** [comment]
Contenido: https://docs.google.com/document/d/1RuLBLzKr0vgIjQmpNv1aXxu8q-vZrFWGu0ySBmBrpu4/edit?usp=sharing

**Comment by jajs1975** [comment]
Te encargo es contenido en Ingles Diego, porfa.

**Comment by jipster** [comment]
Aquí está eli link @jajs1975 https://docs.google.com/a/opengovpartnership.org/document/d/1F3vJrITQKsWXyKtOZf4nOyGmZmcwpJ0Xie8-nfcWcaA/edit?usp=sharing
