### ISSUE TITLE
Agregar sección de Sponsors

### ISSUE THREAD

**Issue by diegobeauroyre** [mxabierto/cumbre-global#110]
Aquí está: https://drive.google.com/a/dhb.mx/folderview?id=0BwdAZw_UiZSTLUYwQ1NGV2x3MkE&usp=sharing

**Comment by diegobeauroyre** [comment]
@jajs1975 ¿Tenemos algún avance de esto?

**Comment by jipster** [comment]
@jajs1975 has sabido algo de esto? están presionando mucho por tener esto arriba

**Comment by diegobeauroyre** [comment]
@jajs1975 Esto si lo podemos ir subiendo
