### ISSUE TITLE
Poner el logo de OGP en el header

### ISSUE THREAD

**Issue by jipster** [mxabierto/cumbre-global#21]
Quitar el loguito de méxico del navbar y poner ahí el logo de OGP
![image](https://cloud.githubusercontent.com/assets/5718530/8287642/ad5b8410-18d6-11e5-9c92-77c3860eccb9.png)

**Comment by diegobeauroyre** [comment]
Ay no por? ni si quiera se puede porque es enoooorme :angry:

**Comment by jipster** [comment]
#zen #compromise #ogp @diegobeauroyre
