### ISSUE TITLE
Ajustes en el diseño

### ISSUE THREAD

**Issue by diegobeauroyre** [mxabierto/cumbre-global#24]

**Comment by diegobeauroyre** [comment]
Pongo aquí los archivos origen y los pngs. @jajs1975 @jipster 

Faltaría la sección de about que pondré más adelante.

LINK: https://drive.google.com/folderview?id=0B6xuFjlJEb0NfnhlTXgxZndsWDlUVXpaMTZHeTZIb0taWnU0VG1DTTh3SW9PcTlXUGVEYUE&usp=sharing

![cumbreglobal_web-08-01](https://cloud.githubusercontent.com/assets/6226604/8321223/cf944f94-19e9-11e5-9218-92baab8ea6eb.png)
![cumbreglobal_web-08-02](https://cloud.githubusercontent.com/assets/6226604/8321224/cf94b51a-19e9-11e5-91dc-d94dbd9f309d.png)

**Comment by jipster** [comment]
@jajs1975 nos confirmas?

**Comment by jipster** [comment]
@diegobeauroyre hay que acomodar los logos de abajo de sitio en orden alfabético;

1. GobREP
2. SFP
3. SRE
4. mx abierto
5. INAI (aquí sale el del IFAI)
6. Art. 19
7. CIDAC
8. Cultura Ecológica
9. Fundar
10. GESOC
11. IMCO
12. SocialTic
13. Transparencia Mexicana

**Comment by jipster** [comment]
@jajs1975 el twitter feed debería de poner #OGP15 #OpenGov #GobiernoAbierto #AGA15 y al usuario @opengovpart y @gobabierto_mx

**Comment by jajs1975** [comment]
Hola @jipster, ya existe una primera versión del nuevo rediseño en el nuevo branch "Rediseño-V1".

Nos agradaría mucho para seguir armando la plantilla bajo las mejores practicas, que nos pudieran proporcionar los siguientes 2 elementos:
1. La imagen de fondo que me comentaron agregar en la parte verde.
2.La sección interna "about" para ver como armar esta index para su reutización posterior.

Gracias.

**Comment by jipster** [comment]
@diegobeauroyre puedes mandarle el re-diseño del about a @jajs1975

**Comment by jipster** [comment]
También @diegobeauroyre puedes mandar el re-diseño también con los cambios de los logos, el rediseño final del index y la página interna del about para que se pueda programar por el equipo de @jajs1975 antes de las 11 am para que quede antes de las 10 AM

**Comment by diegobeauroyre** [comment]
Acá está el Re-diseño. 

https://drive.google.com/folderview?id=0B6xuFjlJEb0NfnhlTXgxZndsWDlUVXpaMTZHeTZIb0taWnU0VG1DTTh3SW9PcTlXUGVEYUE&usp=sharing

Del stream de twitter, necesitaríamos tomar el hashtag #ogp15
 https://twitter.com/search?q=%23ogp15&src=typd
