### ISSUE TITLE
Opciones de compartir de redes sociales en el navbar

### ISSUE THREAD

**Issue by jipster** [mxabierto/cumbre-global#26]
La idea es que se puede compartir desde la página en tres diferentes redes con un texto precargado:

Be part of the Mexico 2015 Open Government Partnership Global Summit | Se parte de la Cumbre Global de la Alianza para el Gobierno Abierto México 2015 | www.ogpsummit.org

en 
Facebook
Twitter
LinkedIn

Como ejemplo se puede revisar las condiciones para compartir: http://www.nytimes.com/2012/09/10/opinion/soda-ban-explained.html?_r=1

**Comment by diegobeauroyre** [comment]
Aquí @jajs1975, sólo falta poner los textos precargados en fb y twitter
