### ISSUE TITLE
Links de Términos y Condiciones y About

### ISSUE THREAD

**Issue by jipster** [mxabierto/cumbre-global#4]
1. Agregar en el link de Términos y Condiciones el siguiente contenido, se recomienda que se haga ogpsummit.org/terms e incluir todo lo que se encuentra en este link goo.gl/x6xoAU

2. Terminos tiene acento Términos

3. En la versión en inglés redireccionar Terms and Conditions también al texto de la versión en español 

4. Linkear el about al link hasta abajo del landing

![image](https://cloud.githubusercontent.com/assets/5718530/8162342/3e9a0770-1342-11e5-80c0-7facfa4c5e1a.png)

**Comment by jajs1975** [comment]
Una pregunta para quedar claros @jipster:

¿Para resolver este issue debo crear una nueva página web (como la de about) en la que incluya todo el contenido (en español) del link que mencionas (goo.gl/x6xoAU), y linkearla del footer en donde se encuentra la leyenda "Terminos y Condiciones?

**Comment by jipster** [comment]
@jajs1975 es correcto, puede basarse en la de Acerca de y si hay algún comentario de diseño @diegobeauroyre ya te dirá los cambios.
