### ISSUE TITLE
En la versión movil/responsive aparece una línea en el navbar

### ISSUE THREAD

**Issue by jipster** [mxabierto/cumbre-global#42]
Creo que está relacionado a que hay dos franjas negras alrededor del sitio y cuando lo reduces de tamaño y las eliminas aparece esa rayita

![image](https://cloud.githubusercontent.com/assets/5718530/8588431/57e2d414-2602-11e5-8d27-d0147338dcf5.png)

![image](https://cloud.githubusercontent.com/assets/5718530/8588417/2789d894-2602-11e5-940c-2e2ef0f33c20.png)

**Comment by diegobeauroyre** [comment]
@jajs1975 Tenemos que remover estas líneas negras, que aún aparecen:

<img width="1140" alt="screen shot 2015-07-10 at 12 37 50 pm" src="https://cloud.githubusercontent.com/assets/6226604/8625223/ef76fb42-2702-11e5-878c-24f4dfc36372.png">

**Comment by diegobeauroyre** [comment]
https://drive.google.com/file/d/0B6xuFjlJEb0NVjZzQXlWR3NmY0E/view?usp=sharing

**Comment by diegobeauroyre** [comment]
@jajs1975 @Jredentor LAS franjas negras siguen siendo un problema: 

<img width="1233" alt="screen shot 2015-07-13 at 7 00 12 pm" src="https://cloud.githubusercontent.com/assets/6226604/8663511/7aceb906-2991-11e5-8f31-e12c4635166f.png">
