### ISSUE TITLE
Logos con mala resolución

### ISSUE THREAD

**Issue by jipster** [mxabierto/cumbre-global#43]
Viéndolo en mi cel no sé que le pasa a los logs e iconos que se ven de mala calidad, especialmente el de OGP, MEXICO y el de twitter

![image](https://cloud.githubusercontent.com/assets/5718530/8588513/47638ad8-2603-11e5-80dd-443c6889ba12.png)

**Comment by diegobeauroyre** [comment]
@jajs1975 Lo mejor es usar SVG en vez de PNG, o tenerlo en 2x en PNG (optimizado para retina). 

En los archivos editables que te mandé están los iconos en vectores, dime si prefieres que te pase los SVGs por separado.

**Comment by diegobeauroyre** [comment]
@jajs1975 

Los logos aún se ven pixeleados. En especial el del la cumbre. ¿Qué podemos hacer? ¿svg? PNG?

**Comment by diegobeauroyre** [comment]
Aquí logos en SVG

https://drive.google.com/folderview?id=0B6xuFjlJEb0NfkRPWG55VExrZ3kzTEtaWXZnWThaWHN4SXpuZ0FXRW1RMHliblBUdVY4N0k&usp=sharing

**Comment by jajs1975** [comment]
Ya esta este issue @diegobeauroyre
