### ISSUE TITLE
El verde es distinto en los hovers y links

### ISSUE THREAD

**Issue by jipster** [mxabierto/cumbre-global#44]
Hay que revisar que cuando el menu del navbar está colapsado tenga el mismo verde de la sección seleccionada y de los links en el textos. siento que son diferentes

![image](https://cloud.githubusercontent.com/assets/5718530/8588556/b0f7534e-2603-11e5-979f-d3d41d707bd6.png)

**Comment by diegobeauroyre** [comment]
Sí, debe ser #00cc99
