### ISSUE TITLE
En ogp-u no sale completa la barra de hasta bajo

### ISSUE THREAD

**Issue by jipster** [mxabierto/cumbre-global#55]
![image](https://cloud.githubusercontent.com/assets/5718530/8686660/d11e7988-2a4d-11e5-9e2e-e787b1daa769.png)

**Comment by jipster** [comment]
también pasa en el about 
![image](https://cloud.githubusercontent.com/assets/5718530/8686691/2d78706c-2a4e-11e5-908f-f10524877dc3.png)

**Comment by jipster** [comment]
@JoseJmnz esto lleva un tiempo sin arreglarse

saludos!

**Comment by jipster** [comment]
@jajs1975 @JoseJmnz creen que puedan ayudarme con esto? ninguno de los issues que hemos mandado en las últimas dos semanas se han mejorado.

por favor confírmennos cuando estén revisados

**Comment by diegobeauroyre** [comment]
@jajs1975 @JoseJmnz Esto quedó pendiente

**Comment by jipster** [comment]
@JRedentor este issue sigue pendiente http://ogpsummit.org/ogpu_es.html
