### ISSUE TITLE
Max width en container general

### ISSUE THREAD

**Issue by diegobeauroyre** [mxabierto/cumbre-global#6]
Necesitamos poner un max width de 960 px o similar para que en widescreen no se vea así:

![screen shot 2015-06-15 at 11 21 38 am](https://cloud.githubusercontent.com/assets/6226604/8164724/85e4712a-1350-11e5-9f5c-99f869ef820a.png)
![screen shot 2015-06-15 at 11 21 28 am](https://cloud.githubusercontent.com/assets/6226604/8164726/875fcd38-1350-11e5-8e5c-e63d296090c6.png)
![screen shot 2015-06-15 at 11 21 15 am](https://cloud.githubusercontent.com/assets/6226604/8164727/890a7476-1350-11e5-822b-6ff9d059cfd0.png)

**Comment by jipster** [comment]
Nos avisas @jajs1975 cuando puedan ir checando estos issues, creo que tenemos varias ideas sobre la página que involucran rediseño.

**Comment by jajs1975** [comment]
Hola @jipster, ya podemos ir revisando todos estos issues....Quieren que ya los vayamos solventando o quieren primero hablar por teléfono con nosotros?

**Comment by jipster** [comment]
@jajs1975 creo que lo mejor será seguir sacando los issues y si se atoran por favor nos llamas. Hay que esperar que @diegobeauroyre nos mande un rediseño del sitio entre hoy y mañana.

**Comment by jajs1975** [comment]
Ok...Esperamos que este este rediseño que comentas para ver este issue.

**Comment by jajs1975** [comment]
Hola @jipster, este issue ya se encuentra solucionado en el nuevo branch "JajsUpdate22Junio".
Favor de validarlo.
