### ISSUE TITLE
Meter el documento de Términos y Condiciones descargable en la sección OGP-U

### ISSUE THREAD

**Issue by alejandrardr** [mxabierto/cumbre-global#60]
https://docs.google.com/document/d/1qb0Py-j119z5BI_VVb1iQMzBwqccXxCzcqqVJUCzGRU/edit

**Comment by alejandrardr** [comment]
El documento de términos y condiciones de la convocatoria OGP-U es este https://docs.google.com/document/d/1qb0Py-j119z5BI_VVb1iQMzBwqccXxCzcqqVJUCzGRU/edit

**Comment by diegobeauroyre** [comment]
@JRedentor Un favor, puedes trabajar en este repositorio en lugar de un fork tuyo porfa? Esto es para poder integrar los cambios en nuestro repositorio.
