### ISSUE TITLE
No existe términos y condiciones en español

### ISSUE THREAD

**Issue by jipster** [mxabierto/cumbre-global#61]
Hay un conflicto. La página que se hizo para los términos y condiciones está actualmente referencia a OGP - U, se necesita integrar el texto del términos que está en https://docs.google.com/document/d/1U4b9yuLGQMLQ8XExebm_WiznyxZiVlf8EkKaEue4rFs/edit?usp=sharing y que si está en http://ogpsummit.org/terms.html

**Comment by jipster** [comment]
@JoseJmnz @jajs1975 si están resueltos los issues podrían cerrarlos para que no se haga un caos y no sepamos que ya se hizo y qué no

**Comment by JRedentor** [comment]
Hola @jipster / @alejandrardr!
Me pueden dar más información sobre si este issue se contrapone con el #60, o cómo se complementan, por favor. Saludos

**Comment by jipster** [comment]
Hola @JRedentor son dos temas completamente diferentes.

1. Si te metes a http://ogpsummit.org/terms_es.html no te manda a términos y condiciones generales del sitio, sino al landing de OGP-U, ahi tendríamos que poner bien a dónde está dirigiendo ese url.
2. Sobre el issue #60 la cosa sería que linkearamos este doc.:tps://docs.google.com/document/d/1qb0Py-j119z5BI_VVb1iQMzBwqccXxCzcqqVJUCzGRU/edit a un texto al final del último párrafo de http://ogpsummit.org/ogpu_es.html que diga "Los estudiantes podrán ser de cualquier Universidad o Instituto de Educación Superior en el país, y deberán acreditar su inscripción vigente. Revisa los términos y condiciones aquí [y aquí se pone el link]"

dime si te queda alguna duda y me marca al 50935300 ext. 7322

**Comment by JRedentor** [comment]
Muchas gracias por la orientación @jipster! Creo que con eso queda bastante clara la diferencia, ya hay un pull request para su revisión.

Saludos.
(FYI @jajs1975 )
