### ISSUE TITLE
Meter el texto "Revisa las bases aquí." en OGPU

### ISSUE THREAD

**Issue by alejandrardr** [mxabierto/cumbre-global#63]
El aquí debe tener un vínculo que lleve a este documento https://docs.google.com/document/d/1osQVbnlsHbHq5W8jTV5eXEFQmp28n_UnrbKAwsL1pVs/edit

**Comment by JRedentor** [comment]
Hola @alejandrardr, este issue creo que ya estaba resuelto. En el cuadro de la derecha en la página de OGP-U, arriba del botón gris "Registro", aparece la liga al documento indicado. Si es así, ¿podrías cerrar este issue @diegobeauroyre, por favor? Saludos.
