### ISSUE TITLE
Agregar logos de Cancillería & SFP

### ISSUE THREAD

**Issue by jipster** [mxabierto/cumbre-global#7]

**Comment by jajs1975** [comment]
Cuales logos? y en donde?

**Comment by jipster** [comment]
este mensaje es también para @diegobeauroyre, falta agregar dentro del footer estos dos logos.

**Comment by jajs1975** [comment]
Ok...Un favor..podrías siempre tagear para quien va dirigido el mensaje....así no me los adjudico siempre :-)
