### ISSUE TITLE
Meter el documento de Términos y Condiciones en la sección OGP-U

### ISSUE THREAD

**Issue by alejandrardr** [mxabierto/cumbre-global#72]
Puede ser una leyenda que diga "Consulta aquí los términos y condiciones" con el link al documento, que es este: https://docs.google.com/document/d/1qb0Py-j119z5BI_VVb1iQMzBwqccXxCzcqqVJUCzGRU/edit

**Comment by JRedentor** [comment]
Hola @alejandrardr !
Ya existe un texto con una liga hacia el documento de términos y condiciones (marcado con un recuadro rojo):
![issue72](https://cloud.githubusercontent.com/assets/8809629/9187043/a815e0e0-3f91-11e5-9e58-590075755b73.jpg)
Necesitas que se modifique ese texto? Saludos.
