### ISSUE TITLE
Agregar sección para Sponsors

### ISSUE THREAD

**Issue by jipster** [mxabierto/cumbre-global#8]
1. Platino
2. Oro
3. Plata
4. Bronce

**Comment by jajs1975** [comment]
Hola @jipster, Como se debería de ver esta sección?

**Comment by jipster** [comment]
hola @jajs1975, esto es más bien una parte por diseñar @diegobeauroyre te manda la propuesta cuando esté

**Comment by jajs1975** [comment]
Ok...La esperamos entonces. Gracias.
